// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for UploadDocumentMultipartBodyKategori.
const (
	FISIK    UploadDocumentMultipartBodyKategori = "FISIK"
	KEUANGAN UploadDocumentMultipartBodyKategori = "KEUANGAN"
)

// AnggaranImportResult defines model for AnggaranImportResult.
type AnggaranImportResult struct {
	AkunUpserted     *int `json:"akun_upserted,omitempty"`
	ProgramsUpserted *int `json:"programs_upserted,omitempty"`
	Sp2dInserted     *int `json:"sp2d_inserted,omitempty"`
}

// DocumentMeta defines model for DocumentMeta.
type DocumentMeta struct {
	Bulan          *int                `json:"bulan,omitempty"`
	CreatedAt      *time.Time          `json:"created_at,omitempty"`
	FileHashSha256 *string             `json:"file_hash_sha256,omitempty"`
	FileSizeBytes  *int                `json:"file_size_bytes,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	JenisDokumen   *string             `json:"jenis_dokumen,omitempty"`
	Kategori       *string             `json:"kategori,omitempty"`
	MimeType       *string             `json:"mime_type,omitempty"`
	OriginalName   *string             `json:"original_name,omitempty"`
	PaketId        *openapi_types.UUID `json:"paket_id,omitempty"`
}

// ImportAnggaranDataMultipartBody defines parameters for ImportAnggaranData.
type ImportAnggaranDataMultipartBody struct {
	File          openapi_types.File `json:"file"`
	TahunAnggaran int                `json:"tahun_anggaran"`
}

// GetAnggaranTreeParams defines parameters for GetAnggaranTree.
type GetAnggaranTreeParams struct {
	Tahun int `form:"tahun" json:"tahun"`
}

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	Bulan        int                                 `json:"bulan"`
	File         openapi_types.File                  `json:"file"`
	JenisDokumen string                              `json:"jenis_dokumen"`
	Kategori     UploadDocumentMultipartBodyKategori `json:"kategori"`
	PaketId      openapi_types.UUID                  `json:"paket_id"`
}

// UploadDocumentMultipartBodyKategori defines parameters for UploadDocument.
type UploadDocumentMultipartBodyKategori string

// CreatePaketJSONBody defines parameters for CreatePaket.
type CreatePaketJSONBody struct {
	AkunIds   *[]openapi_types.UUID `json:"akun_ids,omitempty"`
	Kasatker  string                `json:"kasatker"`
	Lokasi    string                `json:"lokasi"`
	NamaPaket string                `json:"nama_paket"`
	PaguPaket float32               `json:"pagu_paket"`
	Targets   *[]struct {
		Bulan          *int     `json:"bulan,omitempty"`
		PersenFisik    *float32 `json:"persen_fisik,omitempty"`
		PersenKeuangan *float32 `json:"persen_keuangan,omitempty"`
	} `json:"targets,omitempty"`
}

// GetDocumentsByPaketParams defines parameters for GetDocumentsByPaket.
type GetDocumentsByPaketParams struct {
	Bulan *int `form:"bulan,omitempty" json:"bulan,omitempty"`
}

// UpdateRealisasiFisikJSONBody defines parameters for UpdateRealisasiFisik.
type UpdateRealisasiFisikJSONBody struct {
	Bulan          int     `json:"bulan"`
	CatatanKendala *string `json:"catatan_kendala,omitempty"`
	PersenAktual   float32 `json:"persen_aktual"`
}

// ImportAnggaranDataMultipartRequestBody defines body for ImportAnggaranData for multipart/form-data ContentType.
type ImportAnggaranDataMultipartRequestBody ImportAnggaranDataMultipartBody

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// CreatePaketJSONRequestBody defines body for CreatePaket for application/json ContentType.
type CreatePaketJSONRequestBody CreatePaketJSONBody

// UpdateRealisasiFisikJSONRequestBody defines body for UpdateRealisasiFisik for application/json ContentType.
type UpdateRealisasiFisikJSONRequestBody UpdateRealisasiFisikJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Import Anggaran data from Excel/CSV
	// (POST /anggaran/import)
	ImportAnggaranData(ctx echo.Context) error
	// Get Anggaran hierarchy tree
	// (GET /anggaran/tree)
	GetAnggaranTree(ctx echo.Context, params GetAnggaranTreeParams) error
	// Upload a document with CAS deduplication
	// (POST /documents)
	UploadDocument(ctx echo.Context) error
	// Download a document by ID
	// (GET /documents/{id})
	DownloadDocument(ctx echo.Context, id openapi_types.UUID) error
	// Health check endpoint
	// (GET /healthz)
	GetHealthz(ctx echo.Context) error
	// List all paket pekerjaan
	// (GET /paket)
	ListPaket(ctx echo.Context) error
	// Create a new paket pekerjaan
	// (POST /paket)
	CreatePaket(ctx echo.Context) error
	// Get paket by ID
	// (GET /paket/{id})
	GetPaket(ctx echo.Context, id openapi_types.UUID) error
	// Get documents for a paket
	// (GET /paket/{id}/documents)
	GetDocumentsByPaket(ctx echo.Context, id openapi_types.UUID, params GetDocumentsByPaketParams) error
	// Update monthly physical realization
	// (PUT /paket/{id}/realisasi)
	UpdateRealisasiFisik(ctx echo.Context, id openapi_types.UUID) error
	// Readiness check endpoint (checks DB)
	// (GET /readyz)
	GetReadyz(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ImportAnggaranData converts echo context to params.
func (w *ServerInterfaceWrapper) ImportAnggaranData(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportAnggaranData(ctx)
	return err
}

// GetAnggaranTree converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnggaranTree(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnggaranTreeParams
	// ------------- Required query parameter "tahun" -------------

	err = runtime.BindQueryParameter("form", true, true, "tahun", ctx.QueryParams(), &params.Tahun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tahun: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnggaranTree(ctx, params)
	return err
}

// UploadDocument converts echo context to params.
func (w *ServerInterfaceWrapper) UploadDocument(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadDocument(ctx)
	return err
}

// DownloadDocument converts echo context to params.
func (w *ServerInterfaceWrapper) DownloadDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DownloadDocument(ctx, id)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// ListPaket converts echo context to params.
func (w *ServerInterfaceWrapper) ListPaket(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPaket(ctx)
	return err
}

// CreatePaket converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePaket(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePaket(ctx)
	return err
}

// GetPaket converts echo context to params.
func (w *ServerInterfaceWrapper) GetPaket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPaket(ctx, id)
	return err
}

// GetDocumentsByPaket converts echo context to params.
func (w *ServerInterfaceWrapper) GetDocumentsByPaket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDocumentsByPaketParams
	// ------------- Optional query parameter "bulan" -------------

	err = runtime.BindQueryParameter("form", true, false, "bulan", ctx.QueryParams(), &params.Bulan)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter bulan: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDocumentsByPaket(ctx, id, params)
	return err
}

// UpdateRealisasiFisik converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRealisasiFisik(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRealisasiFisik(ctx, id)
	return err
}

// GetReadyz converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadyz(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/anggaran/import", wrapper.ImportAnggaranData)
	router.GET(baseURL+"/anggaran/tree", wrapper.GetAnggaranTree)
	router.POST(baseURL+"/documents", wrapper.UploadDocument)
	router.GET(baseURL+"/documents/:id", wrapper.DownloadDocument)
	router.GET(baseURL+"/healthz", wrapper.GetHealthz)
	router.GET(baseURL+"/paket", wrapper.ListPaket)
	router.POST(baseURL+"/paket", wrapper.CreatePaket)
	router.GET(baseURL+"/paket/:id", wrapper.GetPaket)
	router.GET(baseURL+"/paket/:id/documents", wrapper.GetDocumentsByPaket)
	router.PUT(baseURL+"/paket/:id/realisasi", wrapper.UpdateRealisasiFisik)
	router.GET(baseURL+"/readyz", wrapper.GetReadyz)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXW/bNhT9KwS3hxZw4qTrBsxvTtxmRtbUqNe9FIFxI15bN5ZIlR9p3SL/fSBpKfqy",
	"6zZBsaco5CV5ee45R1f+yhOVF0qitIaPvnKTpJhDeBzL1Qo0yGleKG3foXGZ9eOFVgVqSxiiYO3kwhUG",
	"tUXhB+ymQD7iJC2uUPP7gV+w0pCbb4SZ4oVYkNwdcj8oh9TNLSbWL5qoxOUo7Ru00E3uxmUg+09LNIJF",
	"sYBwp6XSuX/iAiweWcqRV4cZq0mu/JolZbhIwaQLk8KL3/+o7dwKMvQFFzcbG9Ponk6icapzJPoOvEVJ",
	"ZiHU2t+x97Q1WFwpTb2TOeW4iKM9s0rTiiRkCwl5f0QBa7SLg3Lt1sZXFBOnyW7mnlQRikSpNeHY2dT/",
	"R5KPtkN8wGMe3KAxpOTDGVDQJW74vd+S5FL5lQJNoqmwPnDEx7MpWyrN5jSeHc3ez8/GVxeXb9/MJ+Pz",
	"y9mcPZuTsZizcZHRGgyxGcoESINkR6wT/tyfTDbzR+/YcDyb8gG/Q23i+afHJ8cnAdMCJRTER/y349Pj",
	"E+4xtGm4+RC2ehpSEFRgqzLhr+cs+LtMBR/xKLhSfhOwwAdc40eHxp4psYk4SosyLM5dZqkAbYe+RkcC",
	"ohKikrua8PxsFPSGJOhNH/0spE4uyrx3SNInRtor9kPcu7PuusuNxjqrHYYBUyhpYpYvTk5a14SiyCgJ",
	"KA1vjZLNO/6qcclH/Jfhg50Nt1427DWykEOTRXGeGZckaMzSZR6DlzGRZuQZCLYtSCS6y3OPYbVHeSTz",
	"1WBLrXL26nOC2fB8/m8AaGU8XuMKIr/LA0OsxlCjFfbQ4wIrbvzj4zzHNORoUftNt6r66DAUdSuqUBLe",
	"Rn1QQ7BT2uv+krSUV17Upxxu2wLkAmtopIQadJJuQvhuIMTW1c1ukbwvMgWitP+nFMiel8Z3aOf7rBul",
	"yz0Ol6/ej68uxld8wF9P59PLmnZ+1JZ79FltMNhetpZMO/MfE+/pk4m38YLvEW05z1wgBIoo2j+7VK0i",
	"P5FNmYEcmX+XM8g0gtgw/EzGmhZ9I80YMNFYfT6eM4HCVbeqcXlSkbdF5uFXEvc7ZT1Rn2SL0n269u+T",
	"B1mHGu7W9LfYcZDEX1OGrKxlAPdlN+hKWbZUTooWfuWt6gjebNh0sgewFCGz6Zd9BvjXNuSQ/N9eNpoR",
	"PvpwXc8wbsWSFJM1QykKRTK6+jDoZGcaf5OxsxBxSBY+mqkli3s2QQpzkGVxkhW4Rn0LUCdVPOjaq7/X",
	"Ds9DO/uQzi4v3C/EntaeRHgmi7k5qGctmzatYRNtzoBdo+71wEz5fqx3SkIOi6oCPSa4cp1p6fKb6NQW",
	"9AptM/WDbb5AbVAulmRo3bv7NmCNDuSqsUsZ0/et0kSmZc2169YwqxBqXPgRntwkZeAL234KtUgZGcWA",
	"Sfx0ADErvex3uQusNPP/cLcIgUALlH23u/nmJkLT9rR+WJqNzS6AKj882/w0rAb9bWPZHjy2TSzd7+H+",
	"XSCrufApB6wUw67XRA1WjZCR2TpJ4XrbRf9l/66Mex2k/bM4+BRmvO+nDLBgwduRFJBBv11Gx4K1dZD1",
	"+1Xdjcq6N5c94kOuSYeqDsyFuohO1+VHWa6kTbMNK9KNoQQyFur8pd1w1bUWWrm9rcO7GPEEnYPfiSQa",
	"02oe2LPwv2GTs+cRotoOzZ9APlx7hhjUdyUFW5+kkixBxsazKbs75QPudMZHfAgFDe9O+f31/X8BAAD/",
	"/x0XMbbBEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
