// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anggaran.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnggaranDokumenByID = `-- name: GetAnggaranDokumenByID :one
SELECT id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM anggaran_dokumen_bukti
WHERE id = $1
`

func (q *Queries) GetAnggaranDokumenByID(ctx context.Context, id pgtype.UUID) (AnggaranDokumenBukti, error) {
	row := q.db.QueryRow(ctx, getAnggaranDokumenByID, id)
	var i AnggaranDokumenBukti
	err := row.Scan(
		&i.ID,
		&i.AnggaranNodeID,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAnggaranDokumenByNode = `-- name: GetAnggaranDokumenByNode :many
SELECT id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM anggaran_dokumen_bukti
WHERE anggaran_node_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAnggaranDokumenByNode(ctx context.Context, anggaranNodeID pgtype.UUID) ([]AnggaranDokumenBukti, error) {
	rows, err := q.db.Query(ctx, getAnggaranDokumenByNode, anggaranNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnggaranDokumenBukti
	for rows.Next() {
		var i AnggaranDokumenBukti
		if err := rows.Scan(
			&i.ID,
			&i.AnggaranNodeID,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnggaranTree = `-- name: GetAnggaranTree :many
WITH RECURSIVE tree AS (
    SELECT 
        id, parent_id, jenis, kode, uraian, tahun_anggaran, bulan,
        pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini,
        realisasi_sd_periode, persentase_realisasi, sisa_anggaran,
        1 AS level,
        ARRAY[kode]::text[] AS path
    FROM anggaran_node a
    WHERE a.parent_id IS NULL AND a.tahun_anggaran = $1 AND a.bulan = $2

    UNION ALL

    SELECT 
        n.id, n.parent_id, n.jenis, n.kode, n.uraian, n.tahun_anggaran, n.bulan,
        n.pagu_revisi, n.lock_pagu, n.realisasi_periode_lalu, n.realisasi_periode_ini,
        n.realisasi_sd_periode, n.persentase_realisasi, n.sisa_anggaran,
        t.level + 1,
        t.path || n.kode
    FROM anggaran_node n
    JOIN tree t ON n.parent_id = t.id
)
SELECT id, parent_id, jenis, kode, uraian, tahun_anggaran, bulan, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, level, path FROM tree
ORDER BY path
`

type GetAnggaranTreeParams struct {
	TahunAnggaran pgtype.Int4 `json:"tahun_anggaran"`
	Bulan         int32       `json:"bulan"`
}

type GetAnggaranTreeRow struct {
	ID                   pgtype.UUID    `json:"id"`
	ParentID             pgtype.UUID    `json:"parent_id"`
	Jenis                string         `json:"jenis"`
	Kode                 string         `json:"kode"`
	Uraian               string         `json:"uraian"`
	TahunAnggaran        pgtype.Int4    `json:"tahun_anggaran"`
	Bulan                int32          `json:"bulan"`
	PaguRevisi           pgtype.Numeric `json:"pagu_revisi"`
	LockPagu             pgtype.Numeric `json:"lock_pagu"`
	RealisasiPeriodeLalu pgtype.Numeric `json:"realisasi_periode_lalu"`
	RealisasiPeriodeIni  pgtype.Numeric `json:"realisasi_periode_ini"`
	RealisasiSdPeriode   pgtype.Numeric `json:"realisasi_sd_periode"`
	PersentaseRealisasi  pgtype.Numeric `json:"persentase_realisasi"`
	SisaAnggaran         pgtype.Numeric `json:"sisa_anggaran"`
	Level                int32          `json:"level"`
	Path                 []string       `json:"path"`
}

func (q *Queries) GetAnggaranTree(ctx context.Context, arg GetAnggaranTreeParams) ([]GetAnggaranTreeRow, error) {
	rows, err := q.db.Query(ctx, getAnggaranTree, arg.TahunAnggaran, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnggaranTreeRow
	for rows.Next() {
		var i GetAnggaranTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Jenis,
			&i.Kode,
			&i.Uraian,
			&i.TahunAnggaran,
			&i.Bulan,
			&i.PaguRevisi,
			&i.LockPagu,
			&i.RealisasiPeriodeLalu,
			&i.RealisasiPeriodeIni,
			&i.RealisasiSdPeriode,
			&i.PersentaseRealisasi,
			&i.SisaAnggaran,
			&i.Level,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiByAkunAndBulan = `-- name: GetRealisasiByAkunAndBulan :many
SELECT id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at FROM realisasi_anggaran_sp2d
WHERE akun_id = $1 AND bulan = $2
ORDER BY tanggal_sp2d
`

type GetRealisasiByAkunAndBulanParams struct {
	AkunID pgtype.UUID `json:"akun_id"`
	Bulan  int32       `json:"bulan"`
}

func (q *Queries) GetRealisasiByAkunAndBulan(ctx context.Context, arg GetRealisasiByAkunAndBulanParams) ([]RealisasiAnggaranSp2d, error) {
	rows, err := q.db.Query(ctx, getRealisasiByAkunAndBulan, arg.AkunID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RealisasiAnggaranSp2d
	for rows.Next() {
		var i RealisasiAnggaranSp2d
		if err := rows.Scan(
			&i.ID,
			&i.AkunID,
			&i.Bulan,
			&i.NomorSp2d,
			&i.TanggalSp2d,
			&i.NilaiCair,
			&i.Keterangan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnggaranDokumen = `-- name: InsertAnggaranDokumen :one
INSERT INTO anggaran_dokumen_bukti (id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at
`

type InsertAnggaranDokumenParams struct {
	ID             pgtype.UUID `json:"id"`
	AnggaranNodeID pgtype.UUID `json:"anggaran_node_id"`
	FileHashSha256 string      `json:"file_hash_sha256"`
	OriginalName   string      `json:"original_name"`
	MimeType       string      `json:"mime_type"`
	FileSizeBytes  int64       `json:"file_size_bytes"`
	UploadedBy     pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) InsertAnggaranDokumen(ctx context.Context, arg InsertAnggaranDokumenParams) (AnggaranDokumenBukti, error) {
	row := q.db.QueryRow(ctx, insertAnggaranDokumen,
		arg.ID,
		arg.AnggaranNodeID,
		arg.FileHashSha256,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var i AnggaranDokumenBukti
	err := row.Scan(
		&i.ID,
		&i.AnggaranNodeID,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertRealisasiSP2D = `-- name: InsertRealisasiSP2D :one
INSERT INTO realisasi_anggaran_sp2d (id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at
`

type InsertRealisasiSP2DParams struct {
	ID          pgtype.UUID    `json:"id"`
	AkunID      pgtype.UUID    `json:"akun_id"`
	Bulan       int32          `json:"bulan"`
	NomorSp2d   string         `json:"nomor_sp2d"`
	TanggalSp2d pgtype.Date    `json:"tanggal_sp2d"`
	NilaiCair   pgtype.Numeric `json:"nilai_cair"`
	Keterangan  pgtype.Text    `json:"keterangan"`
}

func (q *Queries) InsertRealisasiSP2D(ctx context.Context, arg InsertRealisasiSP2DParams) (RealisasiAnggaranSp2d, error) {
	row := q.db.QueryRow(ctx, insertRealisasiSP2D,
		arg.ID,
		arg.AkunID,
		arg.Bulan,
		arg.NomorSp2d,
		arg.TanggalSp2d,
		arg.NilaiCair,
		arg.Keterangan,
	)
	var i RealisasiAnggaranSp2d
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Bulan,
		&i.NomorSp2d,
		&i.TanggalSp2d,
		&i.NilaiCair,
		&i.Keterangan,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAnggaranNode = `-- name: UpsertAnggaranNode :one
INSERT INTO anggaran_node (
    id, parent_id, jenis, kode, uraian, tahun_anggaran, bulan,
    pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, 
    realisasi_sd_periode, persentase_realisasi, sisa_anggaran
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (id) DO UPDATE SET
    uraian = EXCLUDED.uraian,
    pagu_revisi = EXCLUDED.pagu_revisi,
    lock_pagu = EXCLUDED.lock_pagu,
    realisasi_periode_lalu = EXCLUDED.realisasi_periode_lalu,
    realisasi_periode_ini = EXCLUDED.realisasi_periode_ini,
    realisasi_sd_periode = EXCLUDED.realisasi_sd_periode,
    persentase_realisasi = EXCLUDED.persentase_realisasi,
    sisa_anggaran = EXCLUDED.sisa_anggaran
RETURNING id, parent_id, jenis, kode, uraian, tahun_anggaran, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, bulan
`

type UpsertAnggaranNodeParams struct {
	ID                   pgtype.UUID    `json:"id"`
	ParentID             pgtype.UUID    `json:"parent_id"`
	Jenis                string         `json:"jenis"`
	Kode                 string         `json:"kode"`
	Uraian               string         `json:"uraian"`
	TahunAnggaran        pgtype.Int4    `json:"tahun_anggaran"`
	Bulan                int32          `json:"bulan"`
	PaguRevisi           pgtype.Numeric `json:"pagu_revisi"`
	LockPagu             pgtype.Numeric `json:"lock_pagu"`
	RealisasiPeriodeLalu pgtype.Numeric `json:"realisasi_periode_lalu"`
	RealisasiPeriodeIni  pgtype.Numeric `json:"realisasi_periode_ini"`
	RealisasiSdPeriode   pgtype.Numeric `json:"realisasi_sd_periode"`
	PersentaseRealisasi  pgtype.Numeric `json:"persentase_realisasi"`
	SisaAnggaran         pgtype.Numeric `json:"sisa_anggaran"`
}

func (q *Queries) UpsertAnggaranNode(ctx context.Context, arg UpsertAnggaranNodeParams) (AnggaranNode, error) {
	row := q.db.QueryRow(ctx, upsertAnggaranNode,
		arg.ID,
		arg.ParentID,
		arg.Jenis,
		arg.Kode,
		arg.Uraian,
		arg.TahunAnggaran,
		arg.Bulan,
		arg.PaguRevisi,
		arg.LockPagu,
		arg.RealisasiPeriodeLalu,
		arg.RealisasiPeriodeIni,
		arg.RealisasiSdPeriode,
		arg.PersentaseRealisasi,
		arg.SisaAnggaran,
	)
	var i AnggaranNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Jenis,
		&i.Kode,
		&i.Uraian,
		&i.TahunAnggaran,
		&i.PaguRevisi,
		&i.LockPagu,
		&i.RealisasiPeriodeLalu,
		&i.RealisasiPeriodeIni,
		&i.RealisasiSdPeriode,
		&i.PersentaseRealisasi,
		&i.SisaAnggaran,
		&i.Bulan,
	)
	return i, err
}
