// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: anggaran.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnggaranSnapshot = `-- name: CreateAnggaranSnapshot :exec
INSERT INTO anggaran_history (
    id, anggaran_node_id, parent_id, jenis, kode, uraian, tahun_anggaran,
    pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini,
    realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source, snapshot_periode
)
SELECT 
    gen_random_uuid(), id, parent_id, jenis, kode, uraian, tahun_anggaran,
    pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini,
    realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source, $1
FROM anggaran_node
`

func (q *Queries) CreateAnggaranSnapshot(ctx context.Context, snapshotPeriode string) error {
	_, err := q.db.Exec(ctx, createAnggaranSnapshot, snapshotPeriode)
	return err
}

const deleteAnggaranDokumen = `-- name: DeleteAnggaranDokumen :exec
UPDATE anggaran_dokumen_bukti
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteAnggaranDokumen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnggaranDokumen, id)
	return err
}

const deleteAnggaranSnapshot = `-- name: DeleteAnggaranSnapshot :exec
DELETE FROM anggaran_history WHERE snapshot_periode = $1
`

func (q *Queries) DeleteAnggaranSnapshot(ctx context.Context, snapshotPeriode string) error {
	_, err := q.db.Exec(ctx, deleteAnggaranSnapshot, snapshotPeriode)
	return err
}

const getAnggaranDokumenByID = `-- name: GetAnggaranDokumenByID :one
SELECT id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, deleted_at FROM anggaran_dokumen_bukti
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnggaranDokumenByID(ctx context.Context, id pgtype.UUID) (AnggaranDokumenBukti, error) {
	row := q.db.QueryRow(ctx, getAnggaranDokumenByID, id)
	var i AnggaranDokumenBukti
	err := row.Scan(
		&i.ID,
		&i.AnggaranNodeID,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnggaranDokumenByNode = `-- name: GetAnggaranDokumenByNode :many
SELECT 
    d.id, d.anggaran_node_id, d.file_hash_sha256, d.original_name, 
    d.mime_type, d.file_size_bytes, d.uploaded_by, d.created_at, 
    COALESCE(NULLIF(u.full_name, ''), u.username, 'User Non-Aktif') as uploaded_by_name,
    d.sort_order
FROM anggaran_dokumen_bukti d
LEFT JOIN users u ON d.uploaded_by = u.id
WHERE d.anggaran_node_id = $1
AND d.deleted_at IS NULL
ORDER BY d.sort_order ASC, d.created_at ASC, d.original_name ASC
`

type GetAnggaranDokumenByNodeRow struct {
	ID             pgtype.UUID        `json:"id"`
	AnggaranNodeID pgtype.UUID        `json:"anggaran_node_id"`
	FileHashSha256 string             `json:"file_hash_sha256"`
	OriginalName   string             `json:"original_name"`
	MimeType       string             `json:"mime_type"`
	FileSizeBytes  int64              `json:"file_size_bytes"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UploadedByName string             `json:"uploaded_by_name"`
	SortOrder      int32              `json:"sort_order"`
}

func (q *Queries) GetAnggaranDokumenByNode(ctx context.Context, anggaranNodeID pgtype.UUID) ([]GetAnggaranDokumenByNodeRow, error) {
	rows, err := q.db.Query(ctx, getAnggaranDokumenByNode, anggaranNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnggaranDokumenByNodeRow
	for rows.Next() {
		var i GetAnggaranDokumenByNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.AnggaranNodeID,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UploadedByName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnggaranHistoryTree = `-- name: GetAnggaranHistoryTree :many
WITH RECURSIVE tree AS (
    SELECT
        anggaran_node_id AS id, parent_id, jenis, kode, uraian, tahun_anggaran,
        pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini,
        realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source,
        1 AS level,
        ARRAY[kode]::text[] AS path
    FROM anggaran_history a
    WHERE a.parent_id IS NULL AND a.tahun_anggaran = $1 AND a.snapshot_periode = $2 AND a.source = ANY(string_to_array($3::text, ','))

    UNION ALL

    SELECT
        n.anggaran_node_id, n.parent_id, n.jenis, n.kode, n.uraian, n.tahun_anggaran,
        n.pagu_revisi, n.lock_pagu, n.realisasi_periode_lalu, n.realisasi_periode_ini,
        n.realisasi_sd_periode, n.persentase_realisasi, n.sisa_anggaran, n.source,
        t.level + 1,
        t.path || n.kode
    FROM anggaran_history n
    JOIN tree t ON n.parent_id = t.id
    WHERE n.snapshot_periode = $2 AND n.source = ANY(string_to_array($3::text, ','))
)
SELECT id, parent_id, jenis, kode, uraian, tahun_anggaran, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source, level, path FROM tree
ORDER BY path
`

type GetAnggaranHistoryTreeParams struct {
	TahunAnggaran   pgtype.Int4 `json:"tahun_anggaran"`
	SnapshotPeriode string      `json:"snapshot_periode"`
	Column3         string      `json:"column_3"`
}

type GetAnggaranHistoryTreeRow struct {
	ID                   pgtype.UUID    `json:"id"`
	ParentID             pgtype.UUID    `json:"parent_id"`
	Jenis                string         `json:"jenis"`
	Kode                 string         `json:"kode"`
	Uraian               string         `json:"uraian"`
	TahunAnggaran        pgtype.Int4    `json:"tahun_anggaran"`
	PaguRevisi           pgtype.Numeric `json:"pagu_revisi"`
	LockPagu             pgtype.Numeric `json:"lock_pagu"`
	RealisasiPeriodeLalu pgtype.Numeric `json:"realisasi_periode_lalu"`
	RealisasiPeriodeIni  pgtype.Numeric `json:"realisasi_periode_ini"`
	RealisasiSdPeriode   pgtype.Numeric `json:"realisasi_sd_periode"`
	PersentaseRealisasi  pgtype.Numeric `json:"persentase_realisasi"`
	SisaAnggaran         pgtype.Numeric `json:"sisa_anggaran"`
	Source               pgtype.Text    `json:"source"`
	Level                int32          `json:"level"`
	Path                 []string       `json:"path"`
}

func (q *Queries) GetAnggaranHistoryTree(ctx context.Context, arg GetAnggaranHistoryTreeParams) ([]GetAnggaranHistoryTreeRow, error) {
	rows, err := q.db.Query(ctx, getAnggaranHistoryTree, arg.TahunAnggaran, arg.SnapshotPeriode, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnggaranHistoryTreeRow
	for rows.Next() {
		var i GetAnggaranHistoryTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Jenis,
			&i.Kode,
			&i.Uraian,
			&i.TahunAnggaran,
			&i.PaguRevisi,
			&i.LockPagu,
			&i.RealisasiPeriodeLalu,
			&i.RealisasiPeriodeIni,
			&i.RealisasiSdPeriode,
			&i.PersentaseRealisasi,
			&i.SisaAnggaran,
			&i.Source,
			&i.Level,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnggaranTree = `-- name: GetAnggaranTree :many
WITH RECURSIVE tree AS (
    SELECT 
        id, parent_id, jenis, kode, uraian, tahun_anggaran,
        pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini,
        realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source,
        1 AS level,
        ARRAY[kode]::text[] AS path
    FROM anggaran_node a
    WHERE a.parent_id IS NULL AND a.tahun_anggaran = $1 AND a.source = ANY(string_to_array($2::text, ','))

    UNION ALL

    SELECT 
        n.id, n.parent_id, n.jenis, n.kode, n.uraian, n.tahun_anggaran,
        n.pagu_revisi, n.lock_pagu, n.realisasi_periode_lalu, n.realisasi_periode_ini,
        n.realisasi_sd_periode, n.persentase_realisasi, n.sisa_anggaran, n.source,
        t.level + 1,
        t.path || n.kode
    FROM anggaran_node n
    JOIN tree t ON n.parent_id = t.id
    WHERE n.source = ANY(string_to_array($2::text, ','))
)
SELECT id, parent_id, jenis, kode, uraian, tahun_anggaran, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source, level, path FROM tree
ORDER BY path
`

type GetAnggaranTreeParams struct {
	TahunAnggaran pgtype.Int4 `json:"tahun_anggaran"`
	Column2       string      `json:"column_2"`
}

type GetAnggaranTreeRow struct {
	ID                   pgtype.UUID    `json:"id"`
	ParentID             pgtype.UUID    `json:"parent_id"`
	Jenis                string         `json:"jenis"`
	Kode                 string         `json:"kode"`
	Uraian               string         `json:"uraian"`
	TahunAnggaran        pgtype.Int4    `json:"tahun_anggaran"`
	PaguRevisi           pgtype.Numeric `json:"pagu_revisi"`
	LockPagu             pgtype.Numeric `json:"lock_pagu"`
	RealisasiPeriodeLalu pgtype.Numeric `json:"realisasi_periode_lalu"`
	RealisasiPeriodeIni  pgtype.Numeric `json:"realisasi_periode_ini"`
	RealisasiSdPeriode   pgtype.Numeric `json:"realisasi_sd_periode"`
	PersentaseRealisasi  pgtype.Numeric `json:"persentase_realisasi"`
	SisaAnggaran         pgtype.Numeric `json:"sisa_anggaran"`
	Source               pgtype.Text    `json:"source"`
	Level                int32          `json:"level"`
	Path                 []string       `json:"path"`
}

func (q *Queries) GetAnggaranTree(ctx context.Context, arg GetAnggaranTreeParams) ([]GetAnggaranTreeRow, error) {
	rows, err := q.db.Query(ctx, getAnggaranTree, arg.TahunAnggaran, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnggaranTreeRow
	for rows.Next() {
		var i GetAnggaranTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Jenis,
			&i.Kode,
			&i.Uraian,
			&i.TahunAnggaran,
			&i.PaguRevisi,
			&i.LockPagu,
			&i.RealisasiPeriodeLalu,
			&i.RealisasiPeriodeIni,
			&i.RealisasiSdPeriode,
			&i.PersentaseRealisasi,
			&i.SisaAnggaran,
			&i.Source,
			&i.Level,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableSnapshots = `-- name: GetAvailableSnapshots :many
SELECT DISTINCT snapshot_periode
FROM anggaran_history
WHERE tahun_anggaran = $1
ORDER BY snapshot_periode
`

func (q *Queries) GetAvailableSnapshots(ctx context.Context, tahunAnggaran pgtype.Int4) ([]string, error) {
	rows, err := q.db.Query(ctx, getAvailableSnapshots, tahunAnggaran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var snapshot_periode string
		if err := rows.Scan(&snapshot_periode); err != nil {
			return nil, err
		}
		items = append(items, snapshot_periode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiByAkunAndBulan = `-- name: GetRealisasiByAkunAndBulan :many
SELECT id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at FROM realisasi_anggaran_sp2d
WHERE akun_id = $1 AND bulan = $2
ORDER BY tanggal_sp2d
`

type GetRealisasiByAkunAndBulanParams struct {
	AkunID pgtype.UUID `json:"akun_id"`
	Bulan  int32       `json:"bulan"`
}

func (q *Queries) GetRealisasiByAkunAndBulan(ctx context.Context, arg GetRealisasiByAkunAndBulanParams) ([]RealisasiAnggaranSp2d, error) {
	rows, err := q.db.Query(ctx, getRealisasiByAkunAndBulan, arg.AkunID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RealisasiAnggaranSp2d
	for rows.Next() {
		var i RealisasiAnggaranSp2d
		if err := rows.Scan(
			&i.ID,
			&i.AkunID,
			&i.Bulan,
			&i.NomorSp2d,
			&i.TanggalSp2d,
			&i.NilaiCair,
			&i.Keterangan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnggaranDokumen = `-- name: InsertAnggaranDokumen :one
INSERT INTO anggaran_dokumen_bukti (id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, deleted_at
`

type InsertAnggaranDokumenParams struct {
	ID             pgtype.UUID `json:"id"`
	AnggaranNodeID pgtype.UUID `json:"anggaran_node_id"`
	FileHashSha256 string      `json:"file_hash_sha256"`
	OriginalName   string      `json:"original_name"`
	MimeType       string      `json:"mime_type"`
	FileSizeBytes  int64       `json:"file_size_bytes"`
	UploadedBy     pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) InsertAnggaranDokumen(ctx context.Context, arg InsertAnggaranDokumenParams) (AnggaranDokumenBukti, error) {
	row := q.db.QueryRow(ctx, insertAnggaranDokumen,
		arg.ID,
		arg.AnggaranNodeID,
		arg.FileHashSha256,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var i AnggaranDokumenBukti
	err := row.Scan(
		&i.ID,
		&i.AnggaranNodeID,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRealisasiSP2D = `-- name: InsertRealisasiSP2D :one
INSERT INTO realisasi_anggaran_sp2d (id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at
`

type InsertRealisasiSP2DParams struct {
	ID          pgtype.UUID    `json:"id"`
	AkunID      pgtype.UUID    `json:"akun_id"`
	Bulan       int32          `json:"bulan"`
	NomorSp2d   string         `json:"nomor_sp2d"`
	TanggalSp2d pgtype.Date    `json:"tanggal_sp2d"`
	NilaiCair   pgtype.Numeric `json:"nilai_cair"`
	Keterangan  pgtype.Text    `json:"keterangan"`
}

func (q *Queries) InsertRealisasiSP2D(ctx context.Context, arg InsertRealisasiSP2DParams) (RealisasiAnggaranSp2d, error) {
	row := q.db.QueryRow(ctx, insertRealisasiSP2D,
		arg.ID,
		arg.AkunID,
		arg.Bulan,
		arg.NomorSp2d,
		arg.TanggalSp2d,
		arg.NilaiCair,
		arg.Keterangan,
	)
	var i RealisasiAnggaranSp2d
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Bulan,
		&i.NomorSp2d,
		&i.TanggalSp2d,
		&i.NilaiCair,
		&i.Keterangan,
		&i.CreatedAt,
	)
	return i, err
}

const updateAnggaranDokumenName = `-- name: UpdateAnggaranDokumenName :one
UPDATE anggaran_dokumen_bukti
SET original_name = $1
WHERE id = $2
RETURNING id, anggaran_node_id, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, deleted_at
`

type UpdateAnggaranDokumenNameParams struct {
	OriginalName string      `json:"original_name"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAnggaranDokumenName(ctx context.Context, arg UpdateAnggaranDokumenNameParams) (AnggaranDokumenBukti, error) {
	row := q.db.QueryRow(ctx, updateAnggaranDokumenName, arg.OriginalName, arg.ID)
	var i AnggaranDokumenBukti
	err := row.Scan(
		&i.ID,
		&i.AnggaranNodeID,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLockPagu = `-- name: UpdateLockPagu :one
UPDATE anggaran_node
SET lock_pagu = $1
WHERE id = $2
RETURNING id, parent_id, jenis, kode, uraian, tahun_anggaran, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source
`

type UpdateLockPaguParams struct {
	LockPagu pgtype.Numeric `json:"lock_pagu"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateLockPagu(ctx context.Context, arg UpdateLockPaguParams) (AnggaranNode, error) {
	row := q.db.QueryRow(ctx, updateLockPagu, arg.LockPagu, arg.ID)
	var i AnggaranNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Jenis,
		&i.Kode,
		&i.Uraian,
		&i.TahunAnggaran,
		&i.PaguRevisi,
		&i.LockPagu,
		&i.RealisasiPeriodeLalu,
		&i.RealisasiPeriodeIni,
		&i.RealisasiSdPeriode,
		&i.PersentaseRealisasi,
		&i.SisaAnggaran,
		&i.Source,
	)
	return i, err
}

const upsertAnggaranNode = `-- name: UpsertAnggaranNode :one
INSERT INTO anggaran_node (
    id, parent_id, jenis, kode, uraian, tahun_anggaran,
    pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, 
    realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), kode, source) DO UPDATE SET
    uraian = EXCLUDED.uraian,
    pagu_revisi = EXCLUDED.pagu_revisi,
    lock_pagu = EXCLUDED.lock_pagu,
    realisasi_periode_lalu = EXCLUDED.realisasi_periode_lalu,
    realisasi_periode_ini = EXCLUDED.realisasi_periode_ini,
    realisasi_sd_periode = EXCLUDED.realisasi_sd_periode,
    persentase_realisasi = EXCLUDED.persentase_realisasi,
    sisa_anggaran = EXCLUDED.sisa_anggaran
RETURNING id, parent_id, jenis, kode, uraian, tahun_anggaran, pagu_revisi, lock_pagu, realisasi_periode_lalu, realisasi_periode_ini, realisasi_sd_periode, persentase_realisasi, sisa_anggaran, source
`

type UpsertAnggaranNodeParams struct {
	ID                   pgtype.UUID    `json:"id"`
	ParentID             pgtype.UUID    `json:"parent_id"`
	Jenis                string         `json:"jenis"`
	Kode                 string         `json:"kode"`
	Uraian               string         `json:"uraian"`
	TahunAnggaran        pgtype.Int4    `json:"tahun_anggaran"`
	PaguRevisi           pgtype.Numeric `json:"pagu_revisi"`
	LockPagu             pgtype.Numeric `json:"lock_pagu"`
	RealisasiPeriodeLalu pgtype.Numeric `json:"realisasi_periode_lalu"`
	RealisasiPeriodeIni  pgtype.Numeric `json:"realisasi_periode_ini"`
	RealisasiSdPeriode   pgtype.Numeric `json:"realisasi_sd_periode"`
	PersentaseRealisasi  pgtype.Numeric `json:"persentase_realisasi"`
	SisaAnggaran         pgtype.Numeric `json:"sisa_anggaran"`
	Source               pgtype.Text    `json:"source"`
}

func (q *Queries) UpsertAnggaranNode(ctx context.Context, arg UpsertAnggaranNodeParams) (AnggaranNode, error) {
	row := q.db.QueryRow(ctx, upsertAnggaranNode,
		arg.ID,
		arg.ParentID,
		arg.Jenis,
		arg.Kode,
		arg.Uraian,
		arg.TahunAnggaran,
		arg.PaguRevisi,
		arg.LockPagu,
		arg.RealisasiPeriodeLalu,
		arg.RealisasiPeriodeIni,
		arg.RealisasiSdPeriode,
		arg.PersentaseRealisasi,
		arg.SisaAnggaran,
		arg.Source,
	)
	var i AnggaranNode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Jenis,
		&i.Kode,
		&i.Uraian,
		&i.TahunAnggaran,
		&i.PaguRevisi,
		&i.LockPagu,
		&i.RealisasiPeriodeLalu,
		&i.RealisasiPeriodeIni,
		&i.RealisasiSdPeriode,
		&i.PersentaseRealisasi,
		&i.SisaAnggaran,
		&i.Source,
	)
	return i, err
}
