// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: anggaran.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnggaranTree = `-- name: GetAnggaranTree :many
SELECT
    sp.id AS program_id, sp.kode AS program_kode, sp.uraian AS program_uraian,
    sk.id AS kegiatan_id, sk.kode AS kegiatan_kode, sk.uraian AS kegiatan_uraian,
    so.id AS output_id, so.kode AS output_kode, so.uraian AS output_uraian,
    ss.id AS sub_output_id, ss.kode AS sub_output_kode, ss.uraian AS sub_output_uraian,
    sa.id AS akun_id, sa.kode AS akun_kode, sa.uraian AS akun_uraian,
    sa.pagu, sa.realisasi, sa.sisa
FROM anggaran_program sp
JOIN anggaran_kegiatan sk ON sk.program_id = sp.id
JOIN anggaran_output so ON so.kegiatan_id = sk.id
JOIN anggaran_sub_output ss ON ss.output_id = so.id
JOIN anggaran_akun sa ON sa.sub_output_id = ss.id
WHERE sp.tahun_anggaran = $1
ORDER BY sp.kode, sk.kode, so.kode, ss.kode, sa.kode
`

type GetAnggaranTreeRow struct {
	ProgramID       pgtype.UUID
	ProgramKode     string
	ProgramUraian   string
	KegiatanID      pgtype.UUID
	KegiatanKode    string
	KegiatanUraian  string
	OutputID        pgtype.UUID
	OutputKode      string
	OutputUraian    string
	SubOutputID     pgtype.UUID
	SubOutputKode   string
	SubOutputUraian string
	AkunID          pgtype.UUID
	AkunKode        string
	AkunUraian      string
	Pagu            pgtype.Numeric
	Realisasi       pgtype.Numeric
	Sisa            pgtype.Numeric
}

func (q *Queries) GetAnggaranTree(ctx context.Context, tahunAnggaran int32) ([]GetAnggaranTreeRow, error) {
	rows, err := q.db.Query(ctx, getAnggaranTree, tahunAnggaran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnggaranTreeRow
	for rows.Next() {
		var i GetAnggaranTreeRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.ProgramKode,
			&i.ProgramUraian,
			&i.KegiatanID,
			&i.KegiatanKode,
			&i.KegiatanUraian,
			&i.OutputID,
			&i.OutputKode,
			&i.OutputUraian,
			&i.SubOutputID,
			&i.SubOutputKode,
			&i.SubOutputUraian,
			&i.AkunID,
			&i.AkunKode,
			&i.AkunUraian,
			&i.Pagu,
			&i.Realisasi,
			&i.Sisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiByAkunAndBulan = `-- name: GetRealisasiByAkunAndBulan :many
SELECT id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at FROM realisasi_anggaran_sp2d
WHERE akun_id = $1 AND bulan = $2
ORDER BY tanggal_sp2d
`

type GetRealisasiByAkunAndBulanParams struct {
	AkunID pgtype.UUID
	Bulan  int32
}

func (q *Queries) GetRealisasiByAkunAndBulan(ctx context.Context, arg GetRealisasiByAkunAndBulanParams) ([]RealisasiAnggaranSp2d, error) {
	rows, err := q.db.Query(ctx, getRealisasiByAkunAndBulan, arg.AkunID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RealisasiAnggaranSp2d
	for rows.Next() {
		var i RealisasiAnggaranSp2d
		if err := rows.Scan(
			&i.ID,
			&i.AkunID,
			&i.Bulan,
			&i.NomorSp2d,
			&i.TanggalSp2d,
			&i.NilaiCair,
			&i.Keterangan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnggaranAkun = `-- name: InsertAnggaranAkun :one
INSERT INTO anggaran_akun (id, sub_output_id, kode, uraian, pagu, realisasi, sisa)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, sub_output_id = EXCLUDED.sub_output_id, pagu = EXCLUDED.pagu, realisasi = EXCLUDED.realisasi, sisa = EXCLUDED.sisa
RETURNING id, sub_output_id, kode, uraian, pagu, realisasi, sisa
`

type InsertAnggaranAkunParams struct {
	ID          pgtype.UUID
	SubOutputID pgtype.UUID
	Kode        string
	Uraian      string
	Pagu        pgtype.Numeric
	Realisasi   pgtype.Numeric
	Sisa        pgtype.Numeric
}

func (q *Queries) InsertAnggaranAkun(ctx context.Context, arg InsertAnggaranAkunParams) (AnggaranAkun, error) {
	row := q.db.QueryRow(ctx, insertAnggaranAkun,
		arg.ID,
		arg.SubOutputID,
		arg.Kode,
		arg.Uraian,
		arg.Pagu,
		arg.Realisasi,
		arg.Sisa,
	)
	var i AnggaranAkun
	err := row.Scan(
		&i.ID,
		&i.SubOutputID,
		&i.Kode,
		&i.Uraian,
		&i.Pagu,
		&i.Realisasi,
		&i.Sisa,
	)
	return i, err
}

const insertAnggaranKegiatan = `-- name: InsertAnggaranKegiatan :one
INSERT INTO anggaran_kegiatan (id, program_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, program_id = EXCLUDED.program_id
RETURNING id, program_id, kode, uraian
`

type InsertAnggaranKegiatanParams struct {
	ID        pgtype.UUID
	ProgramID pgtype.UUID
	Kode      string
	Uraian    string
}

func (q *Queries) InsertAnggaranKegiatan(ctx context.Context, arg InsertAnggaranKegiatanParams) (AnggaranKegiatan, error) {
	row := q.db.QueryRow(ctx, insertAnggaranKegiatan,
		arg.ID,
		arg.ProgramID,
		arg.Kode,
		arg.Uraian,
	)
	var i AnggaranKegiatan
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}

const insertAnggaranOutput = `-- name: InsertAnggaranOutput :one
INSERT INTO anggaran_output (id, kegiatan_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, kegiatan_id = EXCLUDED.kegiatan_id
RETURNING id, kegiatan_id, kode, uraian
`

type InsertAnggaranOutputParams struct {
	ID         pgtype.UUID
	KegiatanID pgtype.UUID
	Kode       string
	Uraian     string
}

func (q *Queries) InsertAnggaranOutput(ctx context.Context, arg InsertAnggaranOutputParams) (AnggaranOutput, error) {
	row := q.db.QueryRow(ctx, insertAnggaranOutput,
		arg.ID,
		arg.KegiatanID,
		arg.Kode,
		arg.Uraian,
	)
	var i AnggaranOutput
	err := row.Scan(
		&i.ID,
		&i.KegiatanID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}

const insertAnggaranProgram = `-- name: InsertAnggaranProgram :one
INSERT INTO anggaran_program (id, kode, uraian, tahun_anggaran)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, tahun_anggaran = EXCLUDED.tahun_anggaran
RETURNING id, kode, uraian, tahun_anggaran
`

type InsertAnggaranProgramParams struct {
	ID            pgtype.UUID
	Kode          string
	Uraian        string
	TahunAnggaran int32
}

func (q *Queries) InsertAnggaranProgram(ctx context.Context, arg InsertAnggaranProgramParams) (AnggaranProgram, error) {
	row := q.db.QueryRow(ctx, insertAnggaranProgram,
		arg.ID,
		arg.Kode,
		arg.Uraian,
		arg.TahunAnggaran,
	)
	var i AnggaranProgram
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Uraian,
		&i.TahunAnggaran,
	)
	return i, err
}

const insertAnggaranSubOutput = `-- name: InsertAnggaranSubOutput :one
INSERT INTO anggaran_sub_output (id, output_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, output_id = EXCLUDED.output_id
RETURNING id, output_id, kode, uraian
`

type InsertAnggaranSubOutputParams struct {
	ID       pgtype.UUID
	OutputID pgtype.UUID
	Kode     string
	Uraian   string
}

func (q *Queries) InsertAnggaranSubOutput(ctx context.Context, arg InsertAnggaranSubOutputParams) (AnggaranSubOutput, error) {
	row := q.db.QueryRow(ctx, insertAnggaranSubOutput,
		arg.ID,
		arg.OutputID,
		arg.Kode,
		arg.Uraian,
	)
	var i AnggaranSubOutput
	err := row.Scan(
		&i.ID,
		&i.OutputID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}

const insertRealisasiSP2D = `-- name: InsertRealisasiSP2D :one
INSERT INTO realisasi_anggaran_sp2d (id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at
`

type InsertRealisasiSP2DParams struct {
	ID          pgtype.UUID
	AkunID      pgtype.UUID
	Bulan       int32
	NomorSp2d   string
	TanggalSp2d pgtype.Date
	NilaiCair   pgtype.Numeric
	Keterangan  pgtype.Text
}

func (q *Queries) InsertRealisasiSP2D(ctx context.Context, arg InsertRealisasiSP2DParams) (RealisasiAnggaranSp2d, error) {
	row := q.db.QueryRow(ctx, insertRealisasiSP2D,
		arg.ID,
		arg.AkunID,
		arg.Bulan,
		arg.NomorSp2d,
		arg.TanggalSp2d,
		arg.NilaiCair,
		arg.Keterangan,
	)
	var i RealisasiAnggaranSp2d
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Bulan,
		&i.NomorSp2d,
		&i.TanggalSp2d,
		&i.NilaiCair,
		&i.Keterangan,
		&i.CreatedAt,
	)
	return i, err
}
