// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*) FROM activity_logs
`

func (q *Queries) CountActivityLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    id, user_id, action, target_type, target_id, details, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, action, target_type, target_id, details, ip_address, user_agent, created_at
`

type CreateActivityLogParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Action     string
	TargetType pgtype.Text
	TargetID   pgtype.UUID
	Details    []byte
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT 
    al.id, al.user_id, al.action, al.target_type, al.target_id, al.details, al.ip_address, al.user_agent, al.created_at,
    u.full_name as user_full_name,
    u.username as user_username
FROM activity_logs al
JOIN users u ON al.user_id = u.id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActivityLogsParams struct {
	Limit  int32
	Offset int32
}

type ListActivityLogsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	TargetType   pgtype.Text
	TargetID     pgtype.UUID
	Details      []byte
	IpAddress    pgtype.Text
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UserFullName string
	UserUsername string
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityLogsRow
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UserFullName,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
