// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dipa_dokumen.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDipaDokumen = `-- name: DeleteDipaDokumen :exec
DELETE FROM dipa_dokumen WHERE id = $1
`

func (q *Queries) DeleteDipaDokumen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDipaDokumen, id)
	return err
}

const getDipaDocuments = `-- name: GetDipaDocuments :many
SELECT d.id, d.tahun_anggaran, d.bulan, d.revisi, d.file_hash_sha256, d.original_name, d.mime_type, d.file_size_bytes, d.uploaded_by, d.created_at, u.full_name as uploaded_by_name
FROM dipa_dokumen d
LEFT JOIN users u ON u.id = d.uploaded_by
WHERE d.tahun_anggaran = $1
  AND ($2::int = 0 OR d.bulan = $2)
  AND ($3::int = -1 OR d.revisi = $3)
ORDER BY d.bulan DESC, d.revisi DESC, d.created_at DESC
`

type GetDipaDocumentsParams struct {
	TahunAnggaran int32 `json:"tahun_anggaran"`
	Column2       int32 `json:"column_2"`
	Column3       int32 `json:"column_3"`
}

type GetDipaDocumentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TahunAnggaran  int32              `json:"tahun_anggaran"`
	Bulan          int32              `json:"bulan"`
	Revisi         int32              `json:"revisi"`
	FileHashSha256 string             `json:"file_hash_sha256"`
	OriginalName   string             `json:"original_name"`
	MimeType       string             `json:"mime_type"`
	FileSizeBytes  int64              `json:"file_size_bytes"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UploadedByName pgtype.Text        `json:"uploaded_by_name"`
}

func (q *Queries) GetDipaDocuments(ctx context.Context, arg GetDipaDocumentsParams) ([]GetDipaDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getDipaDocuments, arg.TahunAnggaran, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDipaDocumentsRow
	for rows.Next() {
		var i GetDipaDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TahunAnggaran,
			&i.Bulan,
			&i.Revisi,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDipaDokumenByID = `-- name: GetDipaDokumenByID :one
SELECT id, tahun_anggaran, bulan, revisi, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM dipa_dokumen WHERE id = $1
`

func (q *Queries) GetDipaDokumenByID(ctx context.Context, id pgtype.UUID) (DipaDokuman, error) {
	row := q.db.QueryRow(ctx, getDipaDokumenByID, id)
	var i DipaDokuman
	err := row.Scan(
		&i.ID,
		&i.TahunAnggaran,
		&i.Bulan,
		&i.Revisi,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertDipaDokumen = `-- name: InsertDipaDokumen :one
INSERT INTO dipa_dokumen (id, tahun_anggaran, bulan, revisi, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tahun_anggaran, bulan, revisi, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at
`

type InsertDipaDokumenParams struct {
	ID             pgtype.UUID `json:"id"`
	TahunAnggaran  int32       `json:"tahun_anggaran"`
	Bulan          int32       `json:"bulan"`
	Revisi         int32       `json:"revisi"`
	FileHashSha256 string      `json:"file_hash_sha256"`
	OriginalName   string      `json:"original_name"`
	MimeType       string      `json:"mime_type"`
	FileSizeBytes  int64       `json:"file_size_bytes"`
	UploadedBy     pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) InsertDipaDokumen(ctx context.Context, arg InsertDipaDokumenParams) (DipaDokuman, error) {
	row := q.db.QueryRow(ctx, insertDipaDokumen,
		arg.ID,
		arg.TahunAnggaran,
		arg.Bulan,
		arg.Revisi,
		arg.FileHashSha256,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var i DipaDokuman
	err := row.Scan(
		&i.ID,
		&i.TahunAnggaran,
		&i.Bulan,
		&i.Revisi,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
