// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM dokumen_bukti WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM dokumen_bukti WHERE file_hash_sha256 = $1
`

func (q *Queries) GetDocumentByHash(ctx context.Context, fileHashSha256 string) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, getDocumentByHash, fileHashSha256)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentsByPaket = `-- name: GetDocumentsByPaket :many
SELECT id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM dokumen_bukti
WHERE paket_id = $1
ORDER BY bulan, kategori, created_at DESC
`

func (q *Queries) GetDocumentsByPaket(ctx context.Context, paketID pgtype.UUID) ([]DokumenBukti, error) {
	rows, err := q.db.Query(ctx, getDocumentsByPaket, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DokumenBukti
	for rows.Next() {
		var i DokumenBukti
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.Kategori,
			&i.JenisDokumen,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByPaketAndBulan = `-- name: GetDocumentsByPaketAndBulan :many
SELECT id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at FROM dokumen_bukti
WHERE paket_id = $1 AND bulan = $2
ORDER BY kategori, created_at DESC
`

type GetDocumentsByPaketAndBulanParams struct {
	PaketID pgtype.UUID
	Bulan   int32
}

func (q *Queries) GetDocumentsByPaketAndBulan(ctx context.Context, arg GetDocumentsByPaketAndBulanParams) ([]DokumenBukti, error) {
	rows, err := q.db.Query(ctx, getDocumentsByPaketAndBulan, arg.PaketID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DokumenBukti
	for rows.Next() {
		var i DokumenBukti
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.Kategori,
			&i.JenisDokumen,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO dokumen_bukti (id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at
`

type InsertDocumentParams struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	Kategori       string
	JenisDokumen   string
	FileHashSha256 string
	OriginalName   string
	MimeType       string
	FileSizeBytes  int64
	UploadedBy     pgtype.UUID
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.Kategori,
		arg.JenisDokumen,
		arg.FileHashSha256,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
