// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM dokumen_bukti WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, verification_status, verified_by, verified_at, rejection_reason FROM dokumen_bukti WHERE file_hash_sha256 = $1
`

func (q *Queries) GetDocumentByHash(ctx context.Context, fileHashSha256 string) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, getDocumentByHash, fileHashSha256)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, verification_status, verified_by, verified_at, rejection_reason FROM dokumen_bukti WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}

const getDocumentsByPaket = `-- name: GetDocumentsByPaket :many
SELECT d.id, d.paket_id, d.bulan, d.kategori, d.jenis_dokumen, d.file_hash_sha256, d.original_name, d.mime_type, d.file_size_bytes, d.uploaded_by, d.created_at, d.verification_status, d.verified_by, d.verified_at, d.rejection_reason, u.full_name as verified_by_full_name
FROM dokumen_bukti d
LEFT JOIN users u ON u.id = d.verified_by
WHERE d.paket_id = $1
ORDER BY d.bulan, d.kategori, d.created_at DESC
`

type GetDocumentsByPaketRow struct {
	ID                 pgtype.UUID
	PaketID            pgtype.UUID
	Bulan              int32
	Kategori           string
	JenisDokumen       string
	FileHashSha256     string
	OriginalName       string
	MimeType           string
	FileSizeBytes      int64
	UploadedBy         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	VerificationStatus pgtype.Text
	VerifiedBy         pgtype.UUID
	VerifiedAt         pgtype.Timestamptz
	RejectionReason    pgtype.Text
	VerifiedByFullName pgtype.Text
}

func (q *Queries) GetDocumentsByPaket(ctx context.Context, paketID pgtype.UUID) ([]GetDocumentsByPaketRow, error) {
	rows, err := q.db.Query(ctx, getDocumentsByPaket, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsByPaketRow
	for rows.Next() {
		var i GetDocumentsByPaketRow
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.Kategori,
			&i.JenisDokumen,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionReason,
			&i.VerifiedByFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByPaketAndBulan = `-- name: GetDocumentsByPaketAndBulan :many
SELECT d.id, d.paket_id, d.bulan, d.kategori, d.jenis_dokumen, d.file_hash_sha256, d.original_name, d.mime_type, d.file_size_bytes, d.uploaded_by, d.created_at, d.verification_status, d.verified_by, d.verified_at, d.rejection_reason, u.full_name as verified_by_full_name
FROM dokumen_bukti d
LEFT JOIN users u ON u.id = d.verified_by
WHERE d.paket_id = $1 AND d.bulan = $2
ORDER BY d.kategori, d.created_at DESC
`

type GetDocumentsByPaketAndBulanParams struct {
	PaketID pgtype.UUID
	Bulan   int32
}

type GetDocumentsByPaketAndBulanRow struct {
	ID                 pgtype.UUID
	PaketID            pgtype.UUID
	Bulan              int32
	Kategori           string
	JenisDokumen       string
	FileHashSha256     string
	OriginalName       string
	MimeType           string
	FileSizeBytes      int64
	UploadedBy         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	VerificationStatus pgtype.Text
	VerifiedBy         pgtype.UUID
	VerifiedAt         pgtype.Timestamptz
	RejectionReason    pgtype.Text
	VerifiedByFullName pgtype.Text
}

func (q *Queries) GetDocumentsByPaketAndBulan(ctx context.Context, arg GetDocumentsByPaketAndBulanParams) ([]GetDocumentsByPaketAndBulanRow, error) {
	rows, err := q.db.Query(ctx, getDocumentsByPaketAndBulan, arg.PaketID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsByPaketAndBulanRow
	for rows.Next() {
		var i GetDocumentsByPaketAndBulanRow
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.Kategori,
			&i.JenisDokumen,
			&i.FileHashSha256,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionReason,
			&i.VerifiedByFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO dokumen_bukti (id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, verification_status, verified_by, verified_at, rejection_reason
`

type InsertDocumentParams struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	Kategori       string
	JenisDokumen   string
	FileHashSha256 string
	OriginalName   string
	MimeType       string
	FileSizeBytes  int64
	UploadedBy     pgtype.UUID
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.Kategori,
		arg.JenisDokumen,
		arg.FileHashSha256,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}

const verifyDocument = `-- name: VerifyDocument :one
UPDATE dokumen_bukti
SET 
    verification_status = $1,
    verified_by = $2,
    verified_at = CURRENT_TIMESTAMP,
    rejection_reason = $3
WHERE id = $4
RETURNING id, paket_id, bulan, kategori, jenis_dokumen, file_hash_sha256, original_name, mime_type, file_size_bytes, uploaded_by, created_at, verification_status, verified_by, verified_at, rejection_reason
`

type VerifyDocumentParams struct {
	VerificationStatus pgtype.Text
	VerifiedBy         pgtype.UUID
	RejectionReason    pgtype.Text
	ID                 pgtype.UUID
}

func (q *Queries) VerifyDocument(ctx context.Context, arg VerifyDocumentParams) (DokumenBukti, error) {
	row := q.db.QueryRow(ctx, verifyDocument,
		arg.VerificationStatus,
		arg.VerifiedBy,
		arg.RejectionReason,
		arg.ID,
	)
	var i DokumenBukti
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.Kategori,
		&i.JenisDokumen,
		&i.FileHashSha256,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}
