// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnggaranAkun struct {
	ID          pgtype.UUID
	SubOutputID pgtype.UUID
	Kode        string
	Uraian      string
	Pagu        pgtype.Numeric
	Realisasi   pgtype.Numeric
	Sisa        pgtype.Numeric
}

type AnggaranKegiatan struct {
	ID        pgtype.UUID
	ProgramID pgtype.UUID
	Kode      string
	Uraian    string
}

type AnggaranOutput struct {
	ID         pgtype.UUID
	KegiatanID pgtype.UUID
	Kode       string
	Uraian     string
}

type AnggaranProgram struct {
	ID            pgtype.UUID
	Kode          string
	Uraian        string
	TahunAnggaran int32
}

type AnggaranSubOutput struct {
	ID       pgtype.UUID
	OutputID pgtype.UUID
	Kode     string
	Uraian   string
}

type DokumenBukti struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	Kategori       string
	JenisDokumen   string
	FileHashSha256 string
	OriginalName   string
	MimeType       string
	FileSizeBytes  int64
	UploadedBy     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type PaketAkunMapping struct {
	PaketID pgtype.UUID
	AkunID  pgtype.UUID
}

type PaketPekerjaan struct {
	ID        pgtype.UUID
	NamaPaket string
	Kasatker  string
	Lokasi    string
	PaguPaket pgtype.Numeric
	Status    string
	PpkID     pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PaketRealisasiFisik struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	PersenAktual   pgtype.Numeric
	CatatanKendala pgtype.Text
	UpdatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type PaketTarget struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	PersenKeuangan pgtype.Numeric
	PersenFisik    pgtype.Numeric
}

type RealisasiAnggaranSp2d struct {
	ID          pgtype.UUID
	AkunID      pgtype.UUID
	Bulan       int32
	NomorSp2d   string
	TanggalSp2d pgtype.Date
	NilaiCair   pgtype.Numeric
	Keterangan  pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	FullName     string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
