// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: paket.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaketPekerjaanByID = `-- name: GetPaketPekerjaanByID :one
SELECT id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at FROM paket_pekerjaan WHERE id = $1
`

func (q *Queries) GetPaketPekerjaanByID(ctx context.Context, id pgtype.UUID) (PaketPekerjaan, error) {
	row := q.db.QueryRow(ctx, getPaketPekerjaanByID, id)
	var i PaketPekerjaan
	err := row.Scan(
		&i.ID,
		&i.NamaPaket,
		&i.Kasatker,
		&i.Lokasi,
		&i.PaguPaket,
		&i.Status,
		&i.PpkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaketTargetsByPaketID = `-- name: GetPaketTargetsByPaketID :many
SELECT id, paket_id, bulan, persen_keuangan, persen_fisik FROM paket_target WHERE paket_id = $1 ORDER BY bulan
`

func (q *Queries) GetPaketTargetsByPaketID(ctx context.Context, paketID pgtype.UUID) ([]PaketTarget, error) {
	rows, err := q.db.Query(ctx, getPaketTargetsByPaketID, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketTarget
	for rows.Next() {
		var i PaketTarget
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenKeuangan,
			&i.PersenFisik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiFisikByPaketID = `-- name: GetRealisasiFisikByPaketID :many
SELECT id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by, created_at FROM paket_realisasi_fisik WHERE paket_id = $1 ORDER BY bulan
`

func (q *Queries) GetRealisasiFisikByPaketID(ctx context.Context, paketID pgtype.UUID) ([]PaketRealisasiFisik, error) {
	rows, err := q.db.Query(ctx, getRealisasiFisikByPaketID, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketRealisasiFisik
	for rows.Next() {
		var i PaketRealisasiFisik
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenAktual,
			&i.CatatanKendala,
			&i.UpdatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPaketAkunMapping = `-- name: InsertPaketAkunMapping :exec
INSERT INTO paket_akun_mapping (paket_id, akun_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPaketAkunMappingParams struct {
	PaketID pgtype.UUID
	AkunID  pgtype.UUID
}

func (q *Queries) InsertPaketAkunMapping(ctx context.Context, arg InsertPaketAkunMappingParams) error {
	_, err := q.db.Exec(ctx, insertPaketAkunMapping, arg.PaketID, arg.AkunID)
	return err
}

const insertPaketPekerjaan = `-- name: InsertPaketPekerjaan :one
INSERT INTO paket_pekerjaan (id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at
`

type InsertPaketPekerjaanParams struct {
	ID        pgtype.UUID
	NamaPaket string
	Kasatker  string
	Lokasi    string
	PaguPaket pgtype.Numeric
	Status    string
	PpkID     pgtype.UUID
}

func (q *Queries) InsertPaketPekerjaan(ctx context.Context, arg InsertPaketPekerjaanParams) (PaketPekerjaan, error) {
	row := q.db.QueryRow(ctx, insertPaketPekerjaan,
		arg.ID,
		arg.NamaPaket,
		arg.Kasatker,
		arg.Lokasi,
		arg.PaguPaket,
		arg.Status,
		arg.PpkID,
	)
	var i PaketPekerjaan
	err := row.Scan(
		&i.ID,
		&i.NamaPaket,
		&i.Kasatker,
		&i.Lokasi,
		&i.PaguPaket,
		&i.Status,
		&i.PpkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaketTarget = `-- name: InsertPaketTarget :one
INSERT INTO paket_target (id, paket_id, bulan, persen_keuangan, persen_fisik)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (paket_id, bulan) DO UPDATE SET persen_keuangan = EXCLUDED.persen_keuangan, persen_fisik = EXCLUDED.persen_fisik
RETURNING id, paket_id, bulan, persen_keuangan, persen_fisik
`

type InsertPaketTargetParams struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	PersenKeuangan pgtype.Numeric
	PersenFisik    pgtype.Numeric
}

func (q *Queries) InsertPaketTarget(ctx context.Context, arg InsertPaketTargetParams) (PaketTarget, error) {
	row := q.db.QueryRow(ctx, insertPaketTarget,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.PersenKeuangan,
		arg.PersenFisik,
	)
	var i PaketTarget
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.PersenKeuangan,
		&i.PersenFisik,
	)
	return i, err
}

const listPaketPekerjaan = `-- name: ListPaketPekerjaan :many
SELECT id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at FROM paket_pekerjaan ORDER BY created_at DESC
`

func (q *Queries) ListPaketPekerjaan(ctx context.Context) ([]PaketPekerjaan, error) {
	rows, err := q.db.Query(ctx, listPaketPekerjaan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketPekerjaan
	for rows.Next() {
		var i PaketPekerjaan
		if err := rows.Scan(
			&i.ID,
			&i.NamaPaket,
			&i.Kasatker,
			&i.Lokasi,
			&i.PaguPaket,
			&i.Status,
			&i.PpkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRealisasiFisik = `-- name: UpsertRealisasiFisik :one
INSERT INTO paket_realisasi_fisik (id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (paket_id, bulan) DO UPDATE SET persen_aktual = EXCLUDED.persen_aktual, catatan_kendala = EXCLUDED.catatan_kendala, updated_by = EXCLUDED.updated_by
RETURNING id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by, created_at
`

type UpsertRealisasiFisikParams struct {
	ID             pgtype.UUID
	PaketID        pgtype.UUID
	Bulan          int32
	PersenAktual   pgtype.Numeric
	CatatanKendala pgtype.Text
	UpdatedBy      pgtype.UUID
}

func (q *Queries) UpsertRealisasiFisik(ctx context.Context, arg UpsertRealisasiFisikParams) (PaketRealisasiFisik, error) {
	row := q.db.QueryRow(ctx, upsertRealisasiFisik,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.PersenAktual,
		arg.CatatanKendala,
		arg.UpdatedBy,
	)
	var i PaketRealisasiFisik
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.PersenAktual,
		&i.CatatanKendala,
		&i.UpdatedBy,
		&i.CreatedAt,
	)
	return i, err
}
