// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paket.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePaketAkunMappingByPaket = `-- name: DeletePaketAkunMappingByPaket :exec
DELETE FROM paket_akun_mapping
WHERE paket_id = $1
`

func (q *Queries) DeletePaketAkunMappingByPaket(ctx context.Context, paketID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePaketAkunMappingByPaket, paketID)
	return err
}

const deletePaketPekerjaan = `-- name: DeletePaketPekerjaan :exec
DELETE FROM paket_pekerjaan
WHERE id = $1
`

func (q *Queries) DeletePaketPekerjaan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePaketPekerjaan, id)
	return err
}

const getComplianceMatrix = `-- name: GetComplianceMatrix :many
SELECT 
    p.id, 
    p.nama_paket, 
    p.pagu_paket, 
    COALESCE(SUM(aa.pagu), 0)::numeric as pagu_anggaran,
    COALESCE(SUM(aa.realisasi), 0)::numeric as realisasi_anggaran,
    COALESCE(MAX(rf.persen_aktual), 0)::numeric as realisasi_fisik
FROM paket_pekerjaan p
LEFT JOIN paket_akun_mapping pam ON pam.paket_id = p.id
LEFT JOIN anggaran_akun aa ON aa.id = pam.akun_id
LEFT JOIN anggaran_sub_output aso ON aa.sub_output_id = aso.id
LEFT JOIN anggaran_output ao ON aso.output_id = ao.id
LEFT JOIN anggaran_kegiatan ak ON ao.kegiatan_id = ak.id
LEFT JOIN anggaran_program apr ON ak.program_id = apr.id
LEFT JOIN paket_realisasi_fisik rf ON rf.paket_id = p.id
WHERE (apr.tahun_anggaran = $1 OR $1 = 0 OR apr.tahun_anggaran IS NULL)
GROUP BY p.id
`

type GetComplianceMatrixRow struct {
	ID                pgtype.UUID    `json:"id"`
	NamaPaket         string         `json:"nama_paket"`
	PaguPaket         pgtype.Numeric `json:"pagu_paket"`
	PaguAnggaran      pgtype.Numeric `json:"pagu_anggaran"`
	RealisasiAnggaran pgtype.Numeric `json:"realisasi_anggaran"`
	RealisasiFisik    pgtype.Numeric `json:"realisasi_fisik"`
}

func (q *Queries) GetComplianceMatrix(ctx context.Context, tahunAnggaran int32) ([]GetComplianceMatrixRow, error) {
	rows, err := q.db.Query(ctx, getComplianceMatrix, tahunAnggaran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComplianceMatrixRow
	for rows.Next() {
		var i GetComplianceMatrixRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaPaket,
			&i.PaguPaket,
			&i.PaguAnggaran,
			&i.RealisasiAnggaran,
			&i.RealisasiFisik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComplianceMatrixPaged = `-- name: GetComplianceMatrixPaged :many
SELECT
    p.id,
    p.nama_paket,
    p.pagu_paket,
    COALESCE(ang.pagu_anggaran, 0)::numeric as pagu_anggaran,
    COALESCE(ang.realisasi_anggaran, 0)::numeric as realisasi_anggaran,
    COALESCE(rf.realisasi_fisik, 0)::numeric as realisasi_fisik
FROM paket_pekerjaan p
LEFT JOIN LATERAL (
    SELECT
        COALESCE(SUM(aa.pagu), 0)::numeric as pagu_anggaran,
        COALESCE(SUM(aa.realisasi), 0)::numeric as realisasi_anggaran
    FROM paket_akun_mapping pam
    LEFT JOIN anggaran_akun aa ON aa.id = pam.akun_id
    LEFT JOIN anggaran_sub_output aso ON aa.sub_output_id = aso.id
    LEFT JOIN anggaran_output ao ON aso.output_id = ao.id
    LEFT JOIN anggaran_kegiatan ak ON ao.kegiatan_id = ak.id
    LEFT JOIN anggaran_program apr ON ak.program_id = apr.id
    WHERE pam.paket_id = p.id
      AND (apr.tahun_anggaran = $1 OR $1 = 0 OR apr.tahun_anggaran IS NULL)
) ang ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(MAX(rf.persen_aktual), 0)::numeric as realisasi_fisik
    FROM paket_realisasi_fisik rf
    WHERE rf.paket_id = p.id
) rf ON true
WHERE (
    $1 = 0
    OR NOT EXISTS (
        SELECT 1 FROM paket_akun_mapping pam0
        WHERE pam0.paket_id = p.id
    )
    OR EXISTS (
        SELECT 1
        FROM paket_akun_mapping pam1
        LEFT JOIN anggaran_akun aa1 ON aa1.id = pam1.akun_id
        LEFT JOIN anggaran_sub_output aso1 ON aa1.sub_output_id = aso1.id
        LEFT JOIN anggaran_output ao1 ON aso1.output_id = ao1.id
        LEFT JOIN anggaran_kegiatan ak1 ON ao1.kegiatan_id = ak1.id
        LEFT JOIN anggaran_program apr1 ON ak1.program_id = apr1.id
        WHERE pam1.paket_id = p.id
          AND (apr1.tahun_anggaran = $1 OR apr1.tahun_anggaran IS NULL)
    )
)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetComplianceMatrixPagedParams struct {
	TahunAnggaran int32 `json:"tahun_anggaran"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

type GetComplianceMatrixPagedRow struct {
	ID                pgtype.UUID    `json:"id"`
	NamaPaket         string         `json:"nama_paket"`
	PaguPaket         pgtype.Numeric `json:"pagu_paket"`
	PaguAnggaran      pgtype.Numeric `json:"pagu_anggaran"`
	RealisasiAnggaran pgtype.Numeric `json:"realisasi_anggaran"`
	RealisasiFisik    pgtype.Numeric `json:"realisasi_fisik"`
}

func (q *Queries) GetComplianceMatrixPaged(ctx context.Context, arg GetComplianceMatrixPagedParams) ([]GetComplianceMatrixPagedRow, error) {
	rows, err := q.db.Query(ctx, getComplianceMatrixPaged, arg.TahunAnggaran, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComplianceMatrixPagedRow
	for rows.Next() {
		var i GetComplianceMatrixPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaPaket,
			&i.PaguPaket,
			&i.PaguAnggaran,
			&i.RealisasiAnggaran,
			&i.RealisasiFisik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaketPekerjaanByID = `-- name: GetPaketPekerjaanByID :one
SELECT id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at FROM paket_pekerjaan WHERE id = $1
`

func (q *Queries) GetPaketPekerjaanByID(ctx context.Context, id pgtype.UUID) (PaketPekerjaan, error) {
	row := q.db.QueryRow(ctx, getPaketPekerjaanByID, id)
	var i PaketPekerjaan
	err := row.Scan(
		&i.ID,
		&i.NamaPaket,
		&i.Kasatker,
		&i.Lokasi,
		&i.PaguPaket,
		&i.Status,
		&i.PpkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaketTargetsByPaketID = `-- name: GetPaketTargetsByPaketID :many
SELECT id, paket_id, bulan, persen_keuangan, persen_fisik FROM paket_target WHERE paket_id = $1 ORDER BY bulan
`

func (q *Queries) GetPaketTargetsByPaketID(ctx context.Context, paketID pgtype.UUID) ([]PaketTarget, error) {
	rows, err := q.db.Query(ctx, getPaketTargetsByPaketID, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketTarget
	for rows.Next() {
		var i PaketTarget
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenKeuangan,
			&i.PersenFisik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaketTargetsByPaketIDs = `-- name: GetPaketTargetsByPaketIDs :many
SELECT id, paket_id, bulan, persen_keuangan, persen_fisik
FROM paket_target
WHERE paket_id = ANY($1::uuid[])
ORDER BY paket_id, bulan
`

func (q *Queries) GetPaketTargetsByPaketIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]PaketTarget, error) {
	rows, err := q.db.Query(ctx, getPaketTargetsByPaketIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketTarget
	for rows.Next() {
		var i PaketTarget
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenKeuangan,
			&i.PersenFisik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiFisikByPaketID = `-- name: GetRealisasiFisikByPaketID :many
SELECT rf.id, rf.paket_id, rf.bulan, rf.persen_aktual, rf.catatan_kendala, rf.updated_by, rf.created_at, rf.verification_status, rf.verified_by, rf.verified_at, rf.rejection_reason, u.full_name as verified_by_full_name
FROM paket_realisasi_fisik rf
LEFT JOIN users u ON u.id = rf.verified_by
WHERE rf.paket_id = $1 ORDER BY rf.bulan
`

type GetRealisasiFisikByPaketIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PaketID            pgtype.UUID        `json:"paket_id"`
	Bulan              int32              `json:"bulan"`
	PersenAktual       pgtype.Numeric     `json:"persen_aktual"`
	CatatanKendala     pgtype.Text        `json:"catatan_kendala"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	VerificationStatus pgtype.Text        `json:"verification_status"`
	VerifiedBy         pgtype.UUID        `json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	VerifiedByFullName pgtype.Text        `json:"verified_by_full_name"`
}

func (q *Queries) GetRealisasiFisikByPaketID(ctx context.Context, paketID pgtype.UUID) ([]GetRealisasiFisikByPaketIDRow, error) {
	rows, err := q.db.Query(ctx, getRealisasiFisikByPaketID, paketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRealisasiFisikByPaketIDRow
	for rows.Next() {
		var i GetRealisasiFisikByPaketIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenAktual,
			&i.CatatanKendala,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionReason,
			&i.VerifiedByFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealisasiFisikByPaketIDs = `-- name: GetRealisasiFisikByPaketIDs :many
SELECT rf.id, rf.paket_id, rf.bulan, rf.persen_aktual, rf.catatan_kendala, rf.updated_by, rf.created_at, rf.verification_status, rf.verified_by, rf.verified_at, rf.rejection_reason, u.full_name as verified_by_full_name
FROM paket_realisasi_fisik rf
LEFT JOIN users u ON u.id = rf.verified_by
WHERE rf.paket_id = ANY($1::uuid[])
ORDER BY rf.paket_id, rf.bulan
`

type GetRealisasiFisikByPaketIDsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PaketID            pgtype.UUID        `json:"paket_id"`
	Bulan              int32              `json:"bulan"`
	PersenAktual       pgtype.Numeric     `json:"persen_aktual"`
	CatatanKendala     pgtype.Text        `json:"catatan_kendala"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	VerificationStatus pgtype.Text        `json:"verification_status"`
	VerifiedBy         pgtype.UUID        `json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	VerifiedByFullName pgtype.Text        `json:"verified_by_full_name"`
}

func (q *Queries) GetRealisasiFisikByPaketIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetRealisasiFisikByPaketIDsRow, error) {
	rows, err := q.db.Query(ctx, getRealisasiFisikByPaketIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRealisasiFisikByPaketIDsRow
	for rows.Next() {
		var i GetRealisasiFisikByPaketIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaketID,
			&i.Bulan,
			&i.PersenAktual,
			&i.CatatanKendala,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.VerificationStatus,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RejectionReason,
			&i.VerifiedByFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPaketAkunMapping = `-- name: InsertPaketAkunMapping :exec
INSERT INTO paket_akun_mapping (paket_id, akun_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPaketAkunMappingParams struct {
	PaketID pgtype.UUID `json:"paket_id"`
	AkunID  pgtype.UUID `json:"akun_id"`
}

func (q *Queries) InsertPaketAkunMapping(ctx context.Context, arg InsertPaketAkunMappingParams) error {
	_, err := q.db.Exec(ctx, insertPaketAkunMapping, arg.PaketID, arg.AkunID)
	return err
}

const insertPaketPekerjaan = `-- name: InsertPaketPekerjaan :one
INSERT INTO paket_pekerjaan (id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at
`

type InsertPaketPekerjaanParams struct {
	ID        pgtype.UUID    `json:"id"`
	NamaPaket string         `json:"nama_paket"`
	Kasatker  string         `json:"kasatker"`
	Lokasi    string         `json:"lokasi"`
	PaguPaket pgtype.Numeric `json:"pagu_paket"`
	Status    string         `json:"status"`
	PpkID     pgtype.UUID    `json:"ppk_id"`
}

func (q *Queries) InsertPaketPekerjaan(ctx context.Context, arg InsertPaketPekerjaanParams) (PaketPekerjaan, error) {
	row := q.db.QueryRow(ctx, insertPaketPekerjaan,
		arg.ID,
		arg.NamaPaket,
		arg.Kasatker,
		arg.Lokasi,
		arg.PaguPaket,
		arg.Status,
		arg.PpkID,
	)
	var i PaketPekerjaan
	err := row.Scan(
		&i.ID,
		&i.NamaPaket,
		&i.Kasatker,
		&i.Lokasi,
		&i.PaguPaket,
		&i.Status,
		&i.PpkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaketTarget = `-- name: InsertPaketTarget :one
INSERT INTO paket_target (id, paket_id, bulan, persen_keuangan, persen_fisik)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (paket_id, bulan) DO UPDATE SET persen_keuangan = EXCLUDED.persen_keuangan, persen_fisik = EXCLUDED.persen_fisik
RETURNING id, paket_id, bulan, persen_keuangan, persen_fisik
`

type InsertPaketTargetParams struct {
	ID             pgtype.UUID    `json:"id"`
	PaketID        pgtype.UUID    `json:"paket_id"`
	Bulan          int32          `json:"bulan"`
	PersenKeuangan pgtype.Numeric `json:"persen_keuangan"`
	PersenFisik    pgtype.Numeric `json:"persen_fisik"`
}

func (q *Queries) InsertPaketTarget(ctx context.Context, arg InsertPaketTargetParams) (PaketTarget, error) {
	row := q.db.QueryRow(ctx, insertPaketTarget,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.PersenKeuangan,
		arg.PersenFisik,
	)
	var i PaketTarget
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.PersenKeuangan,
		&i.PersenFisik,
	)
	return i, err
}

const listPaketPekerjaan = `-- name: ListPaketPekerjaan :many
SELECT id, nama_paket, kasatker, lokasi, pagu_paket, status, ppk_id, created_at, updated_at FROM paket_pekerjaan ORDER BY created_at DESC
`

func (q *Queries) ListPaketPekerjaan(ctx context.Context) ([]PaketPekerjaan, error) {
	rows, err := q.db.Query(ctx, listPaketPekerjaan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaketPekerjaan
	for rows.Next() {
		var i PaketPekerjaan
		if err := rows.Scan(
			&i.ID,
			&i.NamaPaket,
			&i.Kasatker,
			&i.Lokasi,
			&i.PaguPaket,
			&i.Status,
			&i.PpkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaketPekerjaan = `-- name: UpdatePaketPekerjaan :exec
UPDATE paket_pekerjaan
SET
    nama_paket = COALESCE($1, nama_paket),
    kasatker = COALESCE($2, kasatker),
    lokasi = COALESCE($3, lokasi),
    pagu_paket = COALESCE($4, pagu_paket),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdatePaketPekerjaanParams struct {
	NamaPaket pgtype.Text    `json:"nama_paket"`
	Kasatker  pgtype.Text    `json:"kasatker"`
	Lokasi    pgtype.Text    `json:"lokasi"`
	PaguPaket pgtype.Numeric `json:"pagu_paket"`
	ID        pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdatePaketPekerjaan(ctx context.Context, arg UpdatePaketPekerjaanParams) error {
	_, err := q.db.Exec(ctx, updatePaketPekerjaan,
		arg.NamaPaket,
		arg.Kasatker,
		arg.Lokasi,
		arg.PaguPaket,
		arg.ID,
	)
	return err
}

const upsertRealisasiFisik = `-- name: UpsertRealisasiFisik :one
INSERT INTO paket_realisasi_fisik (id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (paket_id, bulan) DO UPDATE SET persen_aktual = EXCLUDED.persen_aktual, catatan_kendala = EXCLUDED.catatan_kendala, updated_by = EXCLUDED.updated_by
RETURNING id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by, created_at, verification_status, verified_by, verified_at, rejection_reason
`

type UpsertRealisasiFisikParams struct {
	ID             pgtype.UUID    `json:"id"`
	PaketID        pgtype.UUID    `json:"paket_id"`
	Bulan          int32          `json:"bulan"`
	PersenAktual   pgtype.Numeric `json:"persen_aktual"`
	CatatanKendala pgtype.Text    `json:"catatan_kendala"`
	UpdatedBy      pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpsertRealisasiFisik(ctx context.Context, arg UpsertRealisasiFisikParams) (PaketRealisasiFisik, error) {
	row := q.db.QueryRow(ctx, upsertRealisasiFisik,
		arg.ID,
		arg.PaketID,
		arg.Bulan,
		arg.PersenAktual,
		arg.CatatanKendala,
		arg.UpdatedBy,
	)
	var i PaketRealisasiFisik
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.PersenAktual,
		&i.CatatanKendala,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}

const verifyRealisasiFisik = `-- name: VerifyRealisasiFisik :one
UPDATE paket_realisasi_fisik
SET 
    verification_status = $1,
    verified_by = $2,
    verified_at = CURRENT_TIMESTAMP,
    rejection_reason = $3
WHERE id = $4
RETURNING id, paket_id, bulan, persen_aktual, catatan_kendala, updated_by, created_at, verification_status, verified_by, verified_at, rejection_reason
`

type VerifyRealisasiFisikParams struct {
	VerificationStatus pgtype.Text `json:"verification_status"`
	VerifiedBy         pgtype.UUID `json:"verified_by"`
	RejectionReason    pgtype.Text `json:"rejection_reason"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) VerifyRealisasiFisik(ctx context.Context, arg VerifyRealisasiFisikParams) (PaketRealisasiFisik, error) {
	row := q.db.QueryRow(ctx, verifyRealisasiFisik,
		arg.VerificationStatus,
		arg.VerifiedBy,
		arg.RejectionReason,
		arg.ID,
	)
	var i PaketRealisasiFisik
	err := row.Scan(
		&i.ID,
		&i.PaketID,
		&i.Bulan,
		&i.PersenAktual,
		&i.CatatanKendala,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.VerificationStatus,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RejectionReason,
	)
	return i, err
}
