// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sakti.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRealisasiByAkunAndBulan = `-- name: GetRealisasiByAkunAndBulan :many
SELECT id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at FROM realisasi_sakti_sp2d
WHERE akun_id = $1 AND bulan = $2
ORDER BY tanggal_sp2d
`

type GetRealisasiByAkunAndBulanParams struct {
	AkunID pgtype.UUID
	Bulan  int32
}

func (q *Queries) GetRealisasiByAkunAndBulan(ctx context.Context, arg GetRealisasiByAkunAndBulanParams) ([]RealisasiSaktiSp2d, error) {
	rows, err := q.db.Query(ctx, getRealisasiByAkunAndBulan, arg.AkunID, arg.Bulan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RealisasiSaktiSp2d
	for rows.Next() {
		var i RealisasiSaktiSp2d
		if err := rows.Scan(
			&i.ID,
			&i.AkunID,
			&i.Bulan,
			&i.NomorSp2d,
			&i.TanggalSp2d,
			&i.NilaiCair,
			&i.Keterangan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaktiTree = `-- name: GetSaktiTree :many
SELECT
    sp.id AS program_id, sp.kode AS program_kode, sp.uraian AS program_uraian,
    sk.id AS kegiatan_id, sk.kode AS kegiatan_kode, sk.uraian AS kegiatan_uraian,
    so.id AS output_id, so.kode AS output_kode, so.uraian AS output_uraian,
    ss.id AS sub_output_id, ss.kode AS sub_output_kode, ss.uraian AS sub_output_uraian,
    sa.id AS akun_id, sa.kode AS akun_kode, sa.uraian AS akun_uraian,
    sa.pagu, sa.realisasi, sa.sisa
FROM sakti_program sp
JOIN sakti_kegiatan sk ON sk.program_id = sp.id
JOIN sakti_output so ON so.kegiatan_id = sk.id
JOIN sakti_sub_output ss ON ss.output_id = so.id
JOIN sakti_akun sa ON sa.sub_output_id = ss.id
WHERE sp.tahun_anggaran = $1
ORDER BY sp.kode, sk.kode, so.kode, ss.kode, sa.kode
`

type GetSaktiTreeRow struct {
	ProgramID       pgtype.UUID
	ProgramKode     string
	ProgramUraian   string
	KegiatanID      pgtype.UUID
	KegiatanKode    string
	KegiatanUraian  string
	OutputID        pgtype.UUID
	OutputKode      string
	OutputUraian    string
	SubOutputID     pgtype.UUID
	SubOutputKode   string
	SubOutputUraian string
	AkunID          pgtype.UUID
	AkunKode        string
	AkunUraian      string
	Pagu            pgtype.Numeric
	Realisasi       pgtype.Numeric
	Sisa            pgtype.Numeric
}

func (q *Queries) GetSaktiTree(ctx context.Context, tahunAnggaran int32) ([]GetSaktiTreeRow, error) {
	rows, err := q.db.Query(ctx, getSaktiTree, tahunAnggaran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSaktiTreeRow
	for rows.Next() {
		var i GetSaktiTreeRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.ProgramKode,
			&i.ProgramUraian,
			&i.KegiatanID,
			&i.KegiatanKode,
			&i.KegiatanUraian,
			&i.OutputID,
			&i.OutputKode,
			&i.OutputUraian,
			&i.SubOutputID,
			&i.SubOutputKode,
			&i.SubOutputUraian,
			&i.AkunID,
			&i.AkunKode,
			&i.AkunUraian,
			&i.Pagu,
			&i.Realisasi,
			&i.Sisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRealisasiSP2D = `-- name: InsertRealisasiSP2D :one
INSERT INTO realisasi_sakti_sp2d (id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, akun_id, bulan, nomor_sp2d, tanggal_sp2d, nilai_cair, keterangan, created_at
`

type InsertRealisasiSP2DParams struct {
	ID          pgtype.UUID
	AkunID      pgtype.UUID
	Bulan       int32
	NomorSp2d   string
	TanggalSp2d pgtype.Date
	NilaiCair   pgtype.Numeric
	Keterangan  pgtype.Text
}

func (q *Queries) InsertRealisasiSP2D(ctx context.Context, arg InsertRealisasiSP2DParams) (RealisasiSaktiSp2d, error) {
	row := q.db.QueryRow(ctx, insertRealisasiSP2D,
		arg.ID,
		arg.AkunID,
		arg.Bulan,
		arg.NomorSp2d,
		arg.TanggalSp2d,
		arg.NilaiCair,
		arg.Keterangan,
	)
	var i RealisasiSaktiSp2d
	err := row.Scan(
		&i.ID,
		&i.AkunID,
		&i.Bulan,
		&i.NomorSp2d,
		&i.TanggalSp2d,
		&i.NilaiCair,
		&i.Keterangan,
		&i.CreatedAt,
	)
	return i, err
}

const insertSaktiAkun = `-- name: InsertSaktiAkun :one
INSERT INTO sakti_akun (id, sub_output_id, kode, uraian, pagu, realisasi, sisa)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, sub_output_id = EXCLUDED.sub_output_id, pagu = EXCLUDED.pagu, realisasi = EXCLUDED.realisasi, sisa = EXCLUDED.sisa
RETURNING id, sub_output_id, kode, uraian, pagu, realisasi, sisa
`

type InsertSaktiAkunParams struct {
	ID          pgtype.UUID
	SubOutputID pgtype.UUID
	Kode        string
	Uraian      string
	Pagu        pgtype.Numeric
	Realisasi   pgtype.Numeric
	Sisa        pgtype.Numeric
}

func (q *Queries) InsertSaktiAkun(ctx context.Context, arg InsertSaktiAkunParams) (SaktiAkun, error) {
	row := q.db.QueryRow(ctx, insertSaktiAkun,
		arg.ID,
		arg.SubOutputID,
		arg.Kode,
		arg.Uraian,
		arg.Pagu,
		arg.Realisasi,
		arg.Sisa,
	)
	var i SaktiAkun
	err := row.Scan(
		&i.ID,
		&i.SubOutputID,
		&i.Kode,
		&i.Uraian,
		&i.Pagu,
		&i.Realisasi,
		&i.Sisa,
	)
	return i, err
}

const insertSaktiKegiatan = `-- name: InsertSaktiKegiatan :one
INSERT INTO sakti_kegiatan (id, program_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, program_id = EXCLUDED.program_id
RETURNING id, program_id, kode, uraian
`

type InsertSaktiKegiatanParams struct {
	ID        pgtype.UUID
	ProgramID pgtype.UUID
	Kode      string
	Uraian    string
}

func (q *Queries) InsertSaktiKegiatan(ctx context.Context, arg InsertSaktiKegiatanParams) (SaktiKegiatan, error) {
	row := q.db.QueryRow(ctx, insertSaktiKegiatan,
		arg.ID,
		arg.ProgramID,
		arg.Kode,
		arg.Uraian,
	)
	var i SaktiKegiatan
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}

const insertSaktiOutput = `-- name: InsertSaktiOutput :one
INSERT INTO sakti_output (id, kegiatan_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, kegiatan_id = EXCLUDED.kegiatan_id
RETURNING id, kegiatan_id, kode, uraian
`

type InsertSaktiOutputParams struct {
	ID         pgtype.UUID
	KegiatanID pgtype.UUID
	Kode       string
	Uraian     string
}

func (q *Queries) InsertSaktiOutput(ctx context.Context, arg InsertSaktiOutputParams) (SaktiOutput, error) {
	row := q.db.QueryRow(ctx, insertSaktiOutput,
		arg.ID,
		arg.KegiatanID,
		arg.Kode,
		arg.Uraian,
	)
	var i SaktiOutput
	err := row.Scan(
		&i.ID,
		&i.KegiatanID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}

const insertSaktiProgram = `-- name: InsertSaktiProgram :one
INSERT INTO sakti_program (id, kode, uraian, tahun_anggaran)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, tahun_anggaran = EXCLUDED.tahun_anggaran
RETURNING id, kode, uraian, tahun_anggaran
`

type InsertSaktiProgramParams struct {
	ID            pgtype.UUID
	Kode          string
	Uraian        string
	TahunAnggaran int32
}

func (q *Queries) InsertSaktiProgram(ctx context.Context, arg InsertSaktiProgramParams) (SaktiProgram, error) {
	row := q.db.QueryRow(ctx, insertSaktiProgram,
		arg.ID,
		arg.Kode,
		arg.Uraian,
		arg.TahunAnggaran,
	)
	var i SaktiProgram
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Uraian,
		&i.TahunAnggaran,
	)
	return i, err
}

const insertSaktiSubOutput = `-- name: InsertSaktiSubOutput :one
INSERT INTO sakti_sub_output (id, output_id, kode, uraian)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kode) DO UPDATE SET uraian = EXCLUDED.uraian, output_id = EXCLUDED.output_id
RETURNING id, output_id, kode, uraian
`

type InsertSaktiSubOutputParams struct {
	ID       pgtype.UUID
	OutputID pgtype.UUID
	Kode     string
	Uraian   string
}

func (q *Queries) InsertSaktiSubOutput(ctx context.Context, arg InsertSaktiSubOutputParams) (SaktiSubOutput, error) {
	row := q.db.QueryRow(ctx, insertSaktiSubOutput,
		arg.ID,
		arg.OutputID,
		arg.Kode,
		arg.Uraian,
	)
	var i SaktiSubOutput
	err := row.Scan(
		&i.ID,
		&i.OutputID,
		&i.Kode,
		&i.Uraian,
	)
	return i, err
}
